export const sidebarItems = [
  {
    title: "Getting Started",
    items: [
      {
        title: "Introduction",
        href: "/docs",
      },
      { title: "Installation", href: "/docs/installation" },
    ],
  },
  {
    title: "Funky Components",
    items: [
      { title: "Funky Kit", href: "/docs/funky-kit" },
      { title: "Funky Accordion", href: "/docs/funky-accordion" },
      { title: "Funky Alert", href: "/docs/funky-alert" },
      { title: "Funky Avatar", href: "/docs/funky-avatar" },
      { title: "Funky Badge", href: "/docs/funky-badge" },
      { title: "Funky Button", href: "/docs/funky-button" },
      { title: "Funky Card", href: "/docs/funky-card" },
      { title: "Funky Checkbox", href: "/docs/funky-checkbox" },
      { title: "Funky Dialog", href: "/docs/funky-dialog" },
      { title: "Funky Input", href: "/docs/funky-input" },
      { title: "Funky Label", href: "/docs/funky-label" },
      { title: "Funky Progress", href: "/docs/funky-progress" },
      { title: "Funky Radio Group", href: "/docs/funky-radio-group" },
      { title: "Funky Select", href: "/docs/funky-select" },
      { title: "Funky Separator", href: "/docs/funky-separator" },
      { title: "Funky Sheet", href: "/docs/funky-sheet" },
      { title: "Funky Skeleton", href: "/docs/funky-skeleton" },
      { title: "Funky Slider", href: "/docs/funky-slider" },
      { title: "Funky Switch", href: "/docs/funky-switch" },
      { title: "Funky Table", href: "/docs/funky-table" },
      { title: "Funky Tabs", href: "/docs/funky-tabs" },
      { title: "Funky Textarea", href: "/docs/funky-textarea" },
      { title: "Funky Toggle", href: "/docs/funky-toggle" },
      { title: "Funky Tooltip", href: "/docs/funky-tooltip" },
    ],
  },
  {
    title: "Shadcn Funky Style",
    items: [
      { title: "Accordion", href: "/docs/accordion" },
      { title: "Alert", href: "/docs/alert" },
      { title: "Aspect Ratio", href: "/docs/aspect-ratio" },
      { title: "Avatar", href: "/docs/avatar" },
      { title: "Badge", href: "/docs/badge" },
      { title: "Breadcrumb", href: "/docs/breadcrumb" },
      { title: "Button", href: "/docs/button" },
      { title: "Carousel", href: "/docs/carousel" },
      { title: "Card", href: "/docs/card" },
      { title: "Checkbox", href: "/docs/checkbox" },
      { title: "Collapsible", href: "/docs/collapsible" },
      { title: "Command", href: "/docs/command" },
      { title: "Context Menu", href: "/docs/context-menu" },
      { title: "Dialog", href: "/docs/dialog" },
      { title: "Drawer", href: "/docs/drawer" },
      { title: "Dropdown Menu", href: "/docs/dropdown-menu" },
      { title: "Hover Card", href: "/docs/hover-card" },
      { title: "Input", href: "/docs/input" },
      { title: "Input OTP", href: "/docs/input-otp" },
      { title: "Label", href: "/docs/label" },
      { title: "Menubar", href: "/docs/menubar" },
      { title: "Navigation Menu", href: "/docs/navigation-menu" },
      { title: "Pagination", href: "/docs/pagination" },
      { title: "Popover", href: "/docs/popover" },
      { title: "Progress", href: "/docs/progress" },
      { title: "Radio Group", href: "/docs/radio-group" },
      { title: "Resizable", href: "/docs/resizable" },
      { title: "Scroll Area", href: "/docs/scroll-area" },
      { title: "Separator", href: "/docs/separator" },
      { title: "Select", href: "/docs/select" },
      { title: "Sheet", href: "/docs/sheet" },
      { title: "Skeleton", href: "/docs/skeleton" },
      { title: "Slider", href: "/docs/slider" },
      { title: "Sonner", href: "/docs/sonner" },
      { title: "Switch", href: "/docs/switch" },
      { title: "Table", href: "/docs/table" },
      { title: "Tabs", href: "/docs/tabs" },
      { title: "Textarea", href: "/docs/textarea" },
      { title: "Toast", href: "/docs/toast" },
      { title: "Toggle", href: "/docs/toggle" },
      { title: "Toggle Group", href: "/docs/toggle-group" },
      { title: "Tooltip", href: "/docs/tooltip" },
    ],
  },
  {
    title: "HeroUI Funky Style",
    items: [
      { title: "Hero Demo", href: "/docs/hero-demo" },
      { title: "Hero Forms", href: "/docs/hero-forms" },
      { title: "Hero Data", href: "/docs/hero-data" },
      { title: "Hero Navigation", href: "/docs/hero-navigation" },
      { title: "Hero Feedback", href: "/docs/hero-feedback" },
      { title: "Hero Tables", href: "/docs/hero-tables" },
      { title: "Hero Calendar", href: "/docs/hero-calendar" },
      { title: "Hero Advanced Forms", href: "/docs/hero-advanced-form" },
      { title: "Hero Media", href: "/docs/hero-media" },
    ],
  },
];
